### ISSUE TITLE
Can you share the weight?

### ISSUE THREAD

**Issue by jokasimr** [robgon-art/GANscapes#1]
Hi, great work!

Really beautiful images and good idea to use the CLIP model for quality control.

**Could you share the model weights?** 3 weeks training is a lot of gpu resources, it would be amazing if others could use your work in projects without redoing the training 🙌

Thank you for the interesting article.

**Comment by rob-gonsalves** [comment]
Hi jokasimr,

Thanks for the comments!

Yes, the model weights are shared [here ](https://drive.google.com/file/d/1AHKufJ5o4dQFThFN0A-pJRRC2lzxEH2J/view?usp=sharing )and released under the CC BY-SA license. Please give me a shout-out if you share any results publicly.

Code for downloading and using the model is in the Initialize the System section of the colab. And here:

```
!gdown --id 1AHKufJ5o4dQFThFN0A-pJRRC2lzxEH2J
import pickle
import dnnlib
import dnnlib.tflib as tflib
tflib.init_tf()
network_pkl="GANscapes.pkl"
print('Loading networks from "%s"...' %network_pkl)
with dnnlib.util.open_url(network_pkl) as fp:
  _G, _D, Gs = pickle.load(fp)
```

Cheers,
-Rob

**Comment by jokasimr** [comment]
Thank you!

> give me a shout-out if you share any results publicly.

Will do!

**Comment by robgon-art** [comment]
Closing
